### ISSUE TITLE
Tematika

### ISSUE THREAD

**Issue by jaanos** [PiaM123/APPR-2015-16#1]
Tematiko projekta bo potrebno razširiti ali spremeniti, saj smo zelo podoben [projekt](https://github.com/StekovicZ12/APPR-2014-15) imeli že lani. V vsakem primeru bo potrebno poiskati še podatke v kakšni drugi obliki (HTML, XML, JSON) - tako lahko poskusiš najti npr. še kakšne podatke za tujino.

**Comment by PiaM123** [comment]
Na Wikipediji ne najdem nobene tabele. Ali bo uredu, če tabelo iz statističnega urada uvozim kot html datoteko iz OECD pa kot CSV datoteko?

**Comment by jaanos** [comment]
Če res ne najdeš nobenih podatkov na spletu, potem lahko tudi tako narediš. Vseeno pa imej v mislih, da lahko še naknadno dodaš kakšno tabelo iz kake druge spletne strani, če najdeš kaj primernega.

**Comment by PiaM123** [comment]
Uredu, bom zaenkrat naredila tako in če najdem kaj drugega bom kasneje dodala.
