### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by PiaM123** [PiaM123/APPR-2015-16#12]
Zanima me, kako lahko dodam imena regij na zemljevid.

**Comment by jaanos** [comment]
Besedilo lahko na zemljevid (oziroma katerikoli graf) dodaš s funkcijo `geom_text`. Poglej si  [primer](https://ucilnica.fmf.uni-lj.si/mod/resource/view.php?id=17641) z vaj, ki je na voljo na spletni učilnici.

**Comment by PiaM123** [comment]
Sem poskusila, pa mi ne deluje.

**Comment by PiaM123** [comment]
Sem poskusila, vendar mi ne deluje.

**Comment by jaanos** [comment]
Takole bi šlo:

``` R
ZemljevidIzobrazba <- ggplot() +
  geom_polygon(data = IzobrazbaRegije %>%
                 filter(Izobrazba == "Visoka") %>%
                 right_join(slo, by = c("Regija" = "NAME_1")),
                        aes(x = long, y = lat, group = group, fill = Delež)) +
  ggtitle("Delež visoko izobraženih v posamezni regiji") + 
  scale_fill_continuous(low = "#3f0000", high = "#ff0030") +
  geom_text(data = slo %>% group_by(id, NAME_1) %>%
              summarise(x = mean(long), y = mean(lat)), 
            aes(x = x, y = y, label = NAME_1), size = 3)
```

Pozicije oznak so tukaj dobljene kot povprečje vseh točk, ki določajo rob regije. Če bi jih hotela sama postaviti, bi si lahko pripravila razpredelnico s koordinatami in imenom za vsako regijo (tako kot v primeru za zvezne države ZDA) in to uporabila kot podatke k `geom_text`.

**Comment by PiaM123** [comment]
Najlepša hvala za pomoč.
