### ISSUE TITLE
napredna analiza

### ISSUE THREAD

**Issue by PiaM123** [PiaM123/APPR-2015-16#13]
Rada bi naredila napoved za povprečno mesečno plačo za naslednja leta glede na podatke iz prejšnjih let in me zanima na kakšen način bi to lahko naredila.

**Comment by jaanos** [comment]
Enostaven graf, iz katerega lahko vidiš trende gibanja plač (uporabljen je linearni model, torej premica), lahko narišeš tako:

``` R
ggplot(PlacaPoLetih, aes(x = Leto, y = Plača, color = Izobrazba, shape = Spol)) +
  geom_point() + geom_smooth(method = "lm", fullrange = TRUE) + xlim(2008, 2016)
```

Za natančne številke bo treba zgraditi model na izbrani kombinaciji spola in izobrazbe (podatke bo torej treba filtrirati), nato pa lahko s funkcijo `predict` napoveš vrednosti za izbrana leta. Poglej si zadnje vaje na Tomu za primere.

**Comment by PiaM123** [comment]
Sem filtrirala podatke glede na spol in izobrazbo in me zanima, če sem naredila prav oziroma če je tako mišljeno.

**Comment by jaanos** [comment]
Filtriranje izgleda v redu. Seveda lahko poskusiš še s kakim drugim modelom - če bi želela narisati krivuljo za npr. kvadratni model, lahko pri `geom_smooth` podaš parameter `formula = y ~ x + I(x^2)` (prosti člen se vedno vključi, pri potencah in drugih funkcijah spremenljivke pa je potrebno uporabiti še funkcijo `I`).

**Comment by PiaM123** [comment]
Najlepša hvala, dodala sem še dva kvadratna modela ter napoved za povprečno plačo in iz tega naredila novo tabelo. Zanima me še, kako bi lahko vse podatke iz tabele (torej za oba spola in obe izobrazbi) narisala na en graf. 
Mislim, da sem potem s svojim projektom končala. Se vam zdi vredu ali mislite da bi morala še kaj popraviti?

**Comment by jaanos** [comment]
Mislim, da bo v redu. Bom dodal povezavo na repozitorij za zagovore. S profesorjem se lahko domeniš glede termina zagovora.

**Comment by PiaM123** [comment]
Najlepša hvala. Bom napisala profesorju e-mail.
