### ISSUE TITLE
Uvoz podatkov

### ISSUE THREAD

**Issue by PiaM123** [PiaM123/APPR-2015-16#3]
Imam težave pri uvažanju podatkov iz spletne strani http://stats.oecd.org/Index.aspx?datasetcode=EDU_ENRL_AGE#. V tabelah izberem katere podatke bi rada (spol, leto, stopnja izobrazbe,..) in to shranim kot CSV in ko odprem podatke vidim, da mi je vse pomešalo, jih ne tako lepo razvrsti kot podatke iz statističnega urada.
Imam pa tudi problem pri uvozu podatkov iz statističnega urada v obliki HTML.

**Comment by jaanos** [comment]
To, da so podatki pomešani, načeloma ne bi smel biti problem, saj jih lahko po potrebi urediš v R-ju. Lahko morda naložiš podatke na repozitorij, da vidim točno, kaj imaš?

Glede tabele iz HTML iz statističnega urada si poglej moj drugi komentar pri NabergojV#5.

**Comment by PiaM123** [comment]
Kako pa naložim podatke na repozitorij?
Aha hvala si bom pogledala.

**Comment by jaanos** [comment]
Datoteko postavi v mapo `podatki/` svojega projekta, potem pa jo v RStudiu obkljukaj in vključi v commit.

**Comment by PiaM123** [comment]
Podatke sem vam poslala po e-mailu, ker mi tukaj ni uspelo.

**Comment by jaanos** [comment]
S podatki samimi ni nič narobe - gre za to, da je možnih več spremenljivk, izbrala si pa samo dve. Kar se tiče iskanja po podatkih je celo koristno, da so podatki v taki obliki. Če bi pa želela narediti tabelo po dveh spremenljivkah, pa jo lahko izpelješ iz teh podatkov, npr.

``` R
podatki <- read.csv("podatki/IzobrazbaMoskiNemcija.csv", as.is = TRUE)
starosti <- unique(podatki$Age)
izobrazbe <- unique(podatki$Level.of.education)
tabela <- sapply(starosti, . %>% {filter(podatki, Age == .) %>%
                   {setNames(.$Value, .$Level.of.education)[izobrazbe]}}) %>%
          data.frame()
names(tabela) <- starosti
```

Naj malo pojasnim, kaj se tukaj dogaja: za vsako starost poberemo iz stolpca `Value` ustrezne vrednosti, imena vrstic pa pridejo iz stolpca `Level.of.education`. Ker so te v tabeli pomešane, jih je treba spraviti v fiksen vrstni red, ki ga določa vektor `izobrazbe`. Ta potem tudi določa imena vrstic razpredelnice; imena stolpcev pa dobimo iz vektorja `starosti`.

Seveda bo treba datoteko s podatki postaviti v mapo `podatki/`, da jo bo program našel.
