### ISSUE TITLE
Graf

### ISSUE THREAD

**Issue by PiaM123** [PiaM123/APPR-2015-16#4]
Imam problem pri risanju grafov. Ne vem točno, kako bi morala definirati, da bi program vedel, katere podatke mora dati na katero os.
Zapisala sem:
graf1 <- ggplot(data.frame(x=Stevilo.oseb.z.osnovnosolsko.izobrazbo(MoskiSlovenija), y=row.names(MoskiSlovenija)))
pa mi vrne, da ne more najti teh podatkov.

**Comment by jaanos** [comment]
Najprej bo treba podatke spraviti v ustrezno obliko. Zadnja vrstica je odvečna, starost pa naj bo raje kot stolpec namesto imen vrstic:

``` R
MoskiSlovenija <- uvozi.IzobrazbaMoskiSlovenija()
MoskiSlovenija <- MoskiSlovenija[-nrow(MoskiSlovenija),]
MoskiSlovenija <- data.frame(starost = c("20-24 let", "25-29 let", "30-34 let", "35-39 let"),
                             MoskiSlovenija)
```

Odvisno od tega, kakšne grafe boš risala, bo morda treba to razpredelnico spraviti v tako obliko kot npr. `MoskiNemcija` (torej en stolpec s stopnjo izobrazbe in en s številkami).

Pri risanju z ggplot2 imaš v osnovi dva koraka: najprej določiš podatke, potem pa tip grafa. Pri tebi slednji del manjka, poleg tega pa podatki niso pravilno podani. Tako lahko na primer narišeš stolpčni diagram:

``` R
ggplot(MoskiSlovenija, aes(x = starost, y = Stevilo.oseb.z.osnovnosolsko.izobrazbo)) +
  geom_bar(stat = "identity")
```

**Comment by PiaM123** [comment]
Poskusila sem dodati to
MoskiSlovenija <- MoskiSlovenija[-nrow(MoskiSlovenija),]
MoskiSlovenija <- data.frame(starost = c("20-24 let", "25-29 let", "30-34 let", "35-39 let"),
                             MoskiSlovenija)
v projekt ampak mi javi napako.

**Comment by jaanos** [comment]
Kaj natančno pa ti javi?

**Comment by PiaM123** [comment]
Tole mi izpiše:

Error in data.frame(starost = c("20-24 let", "25-29 let", "30-34 let",  : 
  arguments imply differing number of rows: 4, 3

**Comment by jaanos** [comment]
Izgleda, kot da si prvi ukaz (brisanje zadnje vrstice) izvedla dvakrat. Če poženeš celoten uvoz (ali pa prevedeš poročilo - glej #5), bi ti moralo delovati.

**Comment by PiaM123** [comment]
Tudi če poženem celoten uvoz mi še vedno javlja enako napako, enako napako mi sedaj javi tudi pri poročilu.

**Comment by jaanos** [comment]
Imaš zadnjo verzijo na GitHubu? Meni tvoj uvoz deluje, pri poročilu pa je še vedno vsebina iz vzorca.

**Comment by PiaM123** [comment]
Zdaj sem naložila zadnjo verzijo gor.

**Comment by PiaM123** [comment]
Sem rešila problem, sem videla da mi je manjkala zadnja vrstica. Hvala za pomoč.
