### ISSUE TITLE
poročilo

### ISSUE THREAD

**Issue by PiaM123** [PiaM123/APPR-2015-16#5]
Prosila bi vas, da mi pogledate, če se poročilo prevede tako kot je treba. Hvala.

**Comment by jaanos** [comment]
Poročila ti ne prevede, ker imaš v njem še vsebino iz vzorca. Če to pobrišeš, ti bo prevedlo - seveda lahko to sama preveriš s klikom na _Knit PDF_. Seveda bo treba v poročilo dodati še kak graf.

Da ti v poročilo ne bo izpisovalo obvestil ob uvozu knjižnic, vse klice ukazov `library` in `require` premakni iz `uvoz/uvoz.r` v `lib/libraries.r`. Druga možnost bi bila, da pri bloku, kjer kličeš `uvoz.r`, nastaviš `results='hide'` in `message=FALSE`, da se ta obvestila ne izpisujejo.

Svetujem še, da hiperpovezave postaviš med `<>`, npr.

``` markdown
<http://stats.oecd.org/Index.aspx?datasetcode=EDU_ENRL_AGE#>
```

Tako ti bo v celoti naredilo povezavo, hkrati pa se bo ta prelomila, če je predolga za eno vrstico.

**Comment by PiaM123** [comment]
Kaj vse pa je potrebno izbrisati?
Grafe bom dodala kasneje, ko jih narišem. 
Hvala, sem premaknila ukaze in popravila povezave do spletnih strani.

**Comment by jaanos** [comment]
Pobriši vse od histograma naprej. Potem lahko sama poskusiš prevesti.
