### ISSUE TITLE
Uvoz novih podatkov

### ISSUE THREAD

**Issue by PiaM123** [PiaM123/APPR-2015-16#7]
Dodala sem še dvojne nove podatke vendar imam težave pri uvozu in bi vas prosila, da pogledate kaj moram spremeniti, da bo delovalo.

**Comment by jaanos** [comment]
Glede na to, da je teh podatkov malo, bo morda celo najlažje, če že v Excelu podatke iz teh dveh datotek spraviš v obliko tidy data (#8) - torej en stolpec za izobrazbo, en za spol, en za delovno aktivno prebivalstvo, in en za povprečne plače. Zadnja dva stolpca seveda dobiš iz vrstic trenutnih datotek; preostalih vrstic pa seveda ne potrebuješ. Potem tudi pri uvozu (uporabi `read.csv2` namesto `read.table`) ne bo potrebno podati parametra `col.names`, saj bo glava že v datoteki CSV.

**Comment by PiaM123** [comment]
Najlepša hvala za pomoč, sem rešila problem.
