### ISSUE TITLE
Tidy data

### ISSUE THREAD

**Issue by PiaM123** [PiaM123/APPR-2015-16#8]
Zanima me, kako bi podatke za izobrazbo v Sloveniji spremenila v tidy data.

**Comment by jaanos** [comment]
Lahko narediš nekaj takega:

``` R
izobrazba.slovenija <- data.frame(Spol = c(rep("ženski", 12), rep("moški", 12)),
                                  Starost = c("20-24 let", "25-29 let", "30-34 let", "35-39 let"),
                                  Leto = 2013,
                                  Stopnja.izobrazbe = c("Osnovnošolska izobrazba",
                                                        "Srednješolska izobrazba",
                                                        "Visokošolska izobrazba") %>%
                                    matrix(ncol = 4, nrow = 3) %>% t() %>% as.vector(),
                                  Stevilo.oseb = c(ZenskeSlovenija[-1] %>% as.matrix() %>% as.vector(),
                                                   MoskiSlovenija[-1] %>% as.matrix() %>% as.vector()))
```

Tukaj izkoriščaš to, da imaš podatke lepo urejene v razpredelnicah `ZenskeSlovenija` in `MoskiSlovenija`. Ko podatke pretvoriš v matriko in nato v vektor, se ti razvrstijo po stolpcih. Tako imaš najprej ženske, potem moške; v vsaki vrstici imaš novo starost; izobrazbe pa se pojavljajo v skupinah po 4 (zato jih spraviš v matriko, jo transponiraš, in dobljene stolpce zložiš v vektor).

Tudi podatke za Nemčijo lahko zložiš v skupno razpredelnico; navsezadnje imaš lahko vse podatke v eni razpredelnici (v tem primeru bi dodala še stolpec za državo). Pri tem si lahko pomagaš s funkcijo `union`, ki združi dve razpredelnici (pazi, da imajo iste kategorije ista imena).

**Comment by PiaM123** [comment]
Najlepša hvala za pomoč.
