### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by PiaM123** [PiaM123/APPR-2015-16#9]
Uvozila sem novo tabelo s podatki za izobrazbo po regijah in začela uvažati zemljevid, vendar ne vem kako nadaljevati.

**Comment by jaanos** [comment]
Potrebovala boš funkcijo [`pretvori.zemljevid`](https://gist.github.com/jaanos/841499a08ceece11bdbf), s katero zemljevid pretvoriš v obliko, primerno za ggplot2. Potem lahko dobljeni zemljevid pri risanju združiš s svojimi podatki. Če bi npr. želela prikazati število ljudi z visoko izobrazbo v vsaki regiji, bi lahko naredila nekaj takega:

``` R
slo <- pretvori.zemljevid(zemljevid)
ggplot() + geom_polygon(data = IzobrazbaRegije %>%
                          filter(Izobrazba == "Visoka") %>%
                          right_join(slo, by = c("Regija" = "NAME_1")),
                        aes(x = long, y = lat, group = group,
                            fill = Stevilo.oseb))
```

Najprej torej s `filter` vzameš želene vrstice, nato pa z `right_join` združiš podatke z zemljevidom tako, da se stolpec `Regija` iz tvoje razpredelnice ujema s stolpcem `NAME_1` iz zemljevida (`right_join` pomeni, da se ohranijo vse vrstice iz druge razpredelnice - v tem primeru zemljevida - tudi, če ne bi imele ustreznih vrstic v prvi). Pri `fill` potem podaš še ime stolpca, ki določa barvo regije.

Da ne boš dobivala opozoril, svetujem, da pri uvozu razpredelnice `IzobrazbaRegije` odstraniš parameter `as.is = TRUE`. To bo povzročilo, da se bodo nizi uvozili kot faktorji, kar pa ni problem, saj se imena regij popolnoma ujemajo s tistimi v zemljevidu (torej ni potrebno nič popraviti - tukaj bi namreč faktor predstavljal oviro).

**Comment by PiaM123** [comment]
Sem poskusila tako narediti pa mi javlja napako povezano z right_join.

**Comment by jaanos** [comment]
Manjka ti funkcija [`pretvori.zemljevid`](https://gist.github.com/jaanos/841499a08ceece11bdbf) - morda bo najbolje, da si jo skopiraš kar v `lib/uvozi.zemljevid.r`.

Pri izrisovanju zemljevida sicer dobiš opozorilo, ki se ga pa znebiš tako, da `as.is = TRUE` odstraniš pri uvozu razpredelnice `IzobrazbaRegije` (sedaj si odstranila pri `PlaceAktivnostiSlovenija` - tam lahko tudi pustiš brez tega parametra, saj ti vrednosti ni bilo potrebno popravljati).

**Comment by PiaM123** [comment]
Sedaj sem ugotovila ja da je bila ta funkcija že napisana pa sem jo zbrisala.
Aha to sem pa zgrešila in iz napačnega uvoza pobrisala, hvala.

**Comment by PiaM123** [comment]
Sem dodala funkcijo pa mi vseeno ne deluje.

**Comment by jaanos** [comment]
Kaj natančno pa gre narobe (kakšno napako dobiš)? Meni namreč lepo pokaže zemljevid.

**Comment by PiaM123** [comment]
napiše mi: Regions defined for each Polygons

**Comment by jaanos** [comment]
To je v redu - to obvestilo se prikaže pri pretvarjanju zemljevida.

**Comment by PiaM123** [comment]
Aha najlepša hvala. Kaj pa je potrebno narediti da bo zemljevid tudi izrisalo? Poskusila sem s funkcijo print, pa mi ni delovalo.

**Comment by jaanos** [comment]
Če hočeš zemljevid izrisati s `print`, ga najprej shrani v spremenljivko, tako kot pri ostalih grafih. Seveda hočeš zemljevid imeti v poročilu - v ta namen iz poročila pokliči program `vizualizacija/vizualizacija.r` (podobno kot `libraries.r` in `uvoz.r`), nato pa kodo za izrisovanje zemljevida premakneš v svoj blok v poročilu na mestu, kjer želiš, da se prikaže.

**Comment by PiaM123** [comment]
Najlepša hvala. 
Zanima me samo še, kako lahko spreminjam barve na zemljevidu. Poskusila sem s fill=red, vendar mi kar cel zemljevid pobarva v rdečo in ni več videti posameznih regij.

**Comment by PiaM123** [comment]
Še eno vprašanje imam. Rada bi na zemljevidu narisala delež visoko izobraženih tako da bi število oseb z visoko izobrazbo delila s številom vseh oseb v občini, vendar ne vem kako bi to zapisala.

**Comment by jaanos** [comment]
Če hočeš spreminjati uporabljene barvne odtenke, lahko to narediš npr. s funkcijo `scale_fill_continuous`, ki ji podaš barvi za najnižjo in najvišlo vrednost. Če hočeš risati rdeče odtenke, lahko tako zemljevidu prišteješ npr.

``` R
scale_fill_continuous(low = "#3f0000", high = "#ff0000")
```
